{% set version = "6.0" %}
{% set sha256 = "036d96991646d0449ed0aa952e4fbe21b476ce994abc276e49d30e686708bd37" %}

package:
  name: unzip
  version: {{ version }}

source:
  url: ftp://ftp.info-zip.org/pub/infozip/src/unzip{{ version.replace(".", "") }}.tgz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  script:
   - make CC=$CC D_USE_BZ2=-DUSE_BZIP2 IZ_BZIP2=$PREFIX/lib L_BZ2=-lbz2 prefix="$PREFIX" CF="$CFLAGS -DNO_LCHMOD -I. -DUSE_BZIP2" LFLAGS1="$LDFLAGS" -f unix/Makefile generic
   - make prefix="$PREFIX" -f unix/Makefile install

requirements:
  build:
    - "{{ compiler('c') }}"
    - make
  host:
    - bzip2

test:
  commands:
    - unzip -h
    - zipinfo -h

about:
  home: http://www.info-zip.org/
  license: BSD-like
  license_file: LICENSE
  summary: simple program for unzipping files

extra:
  recipe-maintainers:
    - msarahan
    - jerowe
